services:
  - type: web
    name: palmauth-backend
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: palmauth-db
          property: connectionString

databases:
  - name: palmauth-db
    plan: free
    databaseName: palmauth
